version: "3.9"
services:
  #Zookeeper Service.
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: mtogoo-zookeeper

  #Kafka Service
  kafka:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9092:9092'
      - '29092:29092'

    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes

    container_name: mtogo-kafka-broker

    depends_on:
      - "zookeeper"

  order_db:
    container_name: mtogo_order_postgres
    image: postgres:latest
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders

  restaurant_db:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    container_name: mtogo_restaurant_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty!234
      - POSTGRES_DB=restaurants
    ports:
      - '6969:5432'

  camunda-db:
    container_name: mtogo_camunda_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"

  courier-db:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    container_name: mtogo_courier_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty!234
      - POSTGRES_DB=courier
    ports:
      - '5434:5432'

  customer-postgres:
    container_name: mtogo_customerpostgres
    image: postgres
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5452:5432"
    restart: unless-stopped


  auth-postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth


  auth-service:
    depends_on:
      - auth-postgres
      - gateway
    image: tobiaszimmer/exam_auth_service:main-0.1.0
    ports:
      - "8000:8000"
      - "9000:50051"
    environment:
      POSTGRES_HOST: auth-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: auth
      TOKEN_DURATION_HOURS: 12
      HAS_GATEWAY: "false"
      GRPC_ADDRESS: "0.0.0.0:50051"


  gateway:
    image: tobiaszimmer/exam-api-gateway:main-1.0.0-release
    ports:
      - "9999:8080"
    environment:
      GATEWAY_SERVER_PORT : "8080"
      GATEWAY_USERNAME : "gate_us"
      GATEWAY_PASSWORD : "gate_ps"
      GATEWAY_DB_URL : "r2dbc:postgresql://gateway-postgres-db:5432/postgres"
      GATEWAY_DB_USERNAME: "postgres"
      GATEWAY_DB_PASSWORD: "postgres"
      GATEWAY_FLYWAY_URL : "jdbc:postgresql://gateway-postgres-db:5432/postgres"
      GATEWAY_FLYWAY_USERNAME : "postgres"
      GATEWAY_FLYWAY_PASSWORD : "postgres"
      GATEWAY_KAFKA_BOOTSTRAP_SERVERS : "kafka:29092"
      GATEWAY_AUTH_GRPC_URL : "static://auth-service:50051"
    depends_on:
      - gateway-postgres-db
      - kafka

  gateway-postgres-db:
    container_name: mtogo_gateway-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  exam-camunda-service:
    image: tobiaszimmer/exam-camunda-server:main-1.0.1-release
    environment:
      DB_CONNECTION_STR: "jdbc:postgresql://camunda-db:5432/postgres"
      DB_USERNAME: "postgres"
      DB_POSTGRES: "postgres"
      CAMUNDA_ADMIN_USERNAME: "demo"
      CAMUNDA_ADMIN_PASSWORD: "demo"
      CAMUNDA_ADMIN_EMAIL: "test@test.dk"
      CAMUNDA_ADMIN_FIRSTNAME: "admin"
      CAMUNDA_ADMIN_LASTNAME: "admin"
    ports:
      - "8880:8080"
    depends_on:
      - camunda-db


  restaurant:
    depends_on:
      - restaurant_db
      - exam-camunda-service
      - gateway
    image: tobiaszimmer/exam-restaurant-service:main-1.0.0-release
    environment:
      RESTAURANT_SERVICE_DB : "jdbc:postgresql://restaurant_db:5432/restaurants"
      RESTAURANT_DB_USER: "postgres"
      RESTAURANT_DB_PASSWORD: "Qwerty!234"
      CASE_MANAGEMENT_CAMUNDA_BASE_URL: "http://exam-camunda-service:8080/engine-rest"
      KAFKA_BOOTSTRAP_SERVER: "kafka:29092"
      AUTH_GRPC_HOST: "auth-service"
      AUTH_GRPC_PORT: "50051"
      GRPC_SERVER_PORT: "9791"
      GATEWAY_USERNAME: "gate_us"
      GATEWAY_PASSWORD: "gate_ps"
      SERVER_PORT: "8080"

  customer:
    depends_on:
      - customer-postgres
      - exam-camunda-service
      - gateway
    image : tobiaszimmer/exam-customer-service:env_variables-1.0.2-RELEASE
    environment:
      SERVER_PORT: "8080"
      CAMUNDA_ENGINE_REST: "http://exam-camunda-service:8080/engine-rest"
      CUSTOMER_SERVER_PORT: "8080"
      CUSTOMER_GRPC_SERVER_PORT: "9012"
      AUTH_GRPC_URL: "auth-service:50051"
      GATEWAY_USERNAME: "gate_us"
      GATEWAY_PASSWORD: "gate_ps"
      RESTAURANT_GRPC_URL: "restaurant:9791"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      CUSTOMER_DB_URL: "jdbc:postgresql://customer-postgres:5432/customer"
      CUSTOMER_DB_USER: "customer"
      CUSTOMER_DB_PASSWORD: "postgres"

  courier:
    depends_on:
      - courier-db
      - exam-camunda-service
      - gateway
    image: tobiaszimmer/exam-courier-service:test_frontend-1.0.0-RELEASE
    environment:
      GATEWAY_USERNAME: "gate_us"
      GATEWAY_PASSWORD: "gate_ps"
      COURIER_SERVICE_PORT: "8080"
      COURIER_SERVICE_DB: "jdbc:postgresql://courier-db:5432/courier"
      COURIER_DB_USER: "postgres"
      COURIER_DB_PASSWORD: "Qwerty!234"
      COURIER_SERVICE_DDL_MODE: "update"
      CUSTOMER_GRPC_HOST: "customer"
      CUSTOMER_GRPC_PORT: "9012"
      GATEWAY_AUTH_GRPC_URL: "auth-service:50051"
      AUTH_GRPC_HOST: "auth-service"
      AUTH_GRPC_PORT: "50051"
      KAFKA_BOOTSTRAP_SERVER: "kafka:29092"
      CASE_MANAGEMENT_CAMUNDA_BASE_URL: "http://exam-camunda-service:8080/engine-rest"

  order:
    depends_on:
      - order_db
      - exam-camunda-service
      - gateway
    image: tobiaszimmer/exam-order-service:env_variables-1.0.0-release
    environment:
      GATEWAY_USERNAME: "gate_us"
      GATEWAY_PASSWORD: "gate_ps"
      CASE_MANAGEMENT_CAMUNDA_BASE_URL: "http://exam-camunda-service:8080/engine-rest"
      CAMUNDA_ENGINE_REST: "http://exam-camunda-service:8080/engine-rest"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      ORDER_DB_URL: "jdbc:postgresql://order_db:5432/orders"
      ORDER_DB_USER: "postgres"
      ORDER_DB_PASSWORD: "postgres"
      ORDER_SERVER_PORT: "8080"


volumes:
  zookeeper_data:
  kafka_data: